=== sdacosta13/stendhal_S1Team22/data/conf/ActionsSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definition of simple elements -->
	<xs:element name="paramNull" />
	<xs:element name="errorOnRemainder" />
	<xs:element name="maxParam" />
	<xs:element name="minParam" />
	<!-- definition of attributes -->
	<xs:attribute name="value" type="xs:string" />
	<xs:attribute name="index" type="xs:string" />
	<xs:attribute name="optional" type="xs:string" />

	<!-- definition of complex elements -->
	<xs:element name="key">
		<xs:complexType>
			<xs:attribute ref="value" />
		</xs:complexType>
	</xs:element>

	<xs:element name="value">
		<xs:complexType>
			<xs:attribute ref="value" />
			<xs:attribute ref="index" />
		</xs:complexType>
	</xs:element>

	<xs:element name="keypair">

		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" minOccurs="1" maxOccurs="1" />
				<xs:element ref="value" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute ref="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paramNull" minOccurs="0" maxOccurs="1" />
				<xs:element ref="errorOnRemainder" minOccurs="0"
					maxOccurs="1" />
				<xs:element ref="keypair" maxOccurs="unbounded" />
				<xs:element ref="maxParam" minOccurs="1" maxOccurs="1" />
				<xs:element ref="minParam" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/SentenceAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<paramNull></paramNull>
	<keypair>
		<key value="type"></key>
		<value value="sentence"></value>
	</keypair>
	<keypair>
		<key value="value"></key>
		<value value="remainder"></value>
	</keypair>
	<maxParam value="0"></maxParam>
	<minParam value="0"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/CreateChallengeAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<paramNull></paramNull>
	<keypair>
		<key value = "type"/>
		<value value="challenge"/>
	</keypair>
	<keypair>
		<key value = "action"/>
		<value value="open"/>
	</keypair>
	<keypair>
		<key value="target"/>
		<value value="params" index="0"/>
	</keypair>
	<maxParam value="1"></maxParam>
	<minParam value="1"></minParam>
</action>
