=== sdacosta13/stendhal_S1Team22/data/conf/ActionsSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definition of simple elements -->
	<xs:element name="paramNull" />
	<xs:element name="errorOnRemainder" />
	<xs:element name="maxParam" />
	<xs:element name="minParam" />
	<!-- definition of attributes -->
	<xs:attribute name="value" type="xs:string" />
	<xs:attribute name="index" type="xs:string" />
	<xs:attribute name="optional" type="xs:string" />

	<!-- definition of complex elements -->
	<xs:element name="key">
		<xs:complexType>
			<xs:attribute ref="value" />
		</xs:complexType>
	</xs:element>

	<xs:element name="value">
		<xs:complexType>
			<xs:attribute ref="value" />
			<xs:attribute ref="index" />
		</xs:complexType>
	</xs:element>

	<xs:element name="keypair">

		<xs:complexType>
			<xs:sequence>
				<xs:element ref="key" minOccurs="1" maxOccurs="1" />
				<xs:element ref="value" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute ref="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paramNull" minOccurs="0" maxOccurs="1" />
				<xs:element ref="errorOnRemainder" minOccurs="0"
					maxOccurs="1" />
				<xs:element ref="keypair" maxOccurs="unbounded" />
				<xs:element ref="maxParam" minOccurs="1" maxOccurs="1" />
				<xs:element ref="minParam" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/AlterAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<paramNull></paramNull>
	<errorOnRemainder></errorOnRemainder>
	<keypair>
		<key value = "type"/>
		<value value="alter"/>
	</keypair>
	<keypair>
		<key value="target"/>
		<value value="params" index="0"/>
	</keypair>
	<keypair>
		<key value="stat"/>
		<value value="params" index="1"/>
	</keypair>	
	<keypair>
		<key value="mode"/>
		<value value="params" index="2"/>
	</keypair>
	<keypair>
		<key value="value"></key>
		<value value="remainder"></value>
	</keypair>
	<maxParam value="3"></maxParam>
	<minParam value="3"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/InspectQuestAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<keypair>
		<key value="type"></key>
		<value value="INSPECTQUEST"></value>
	</keypair>
	<keypair>
		<key value="target"></key>
		<value value="params" index="0"></value>
	</keypair>
	<keypair>
		<key value="quest_slot"></key>
		<value value="params" index="1"></value>
	</keypair>
	<maxParam value="2"></maxParam>
	<minParam value="2"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/TeleportToAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<keypair>
		<key value="type"></key>
		<value value="teleportto"></value>
	</keypair>
	<keypair>
		<key value="target"></key>
		<value value="remainder"></value>
	</keypair>
	<maxParam value="0"></maxParam>
	<minParam value="0"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/AlterCreatureAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<paramNull></paramNull>
	<keypair>
		<key value = "type"/>
		<value value="altercreature"/>
	</keypair>
	<keypair>
		<key value="target"/>
		<value value="params" index="0"/>
	</keypair>
	<keypair>
		<key value="text"/>
		<value value="params" index="1"/>
	</keypair>
	<maxParam value="2"></maxParam>
	<minParam value="2"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/AdminLevelAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<keypair>
		<key value = "type"/>
		<value value="adminlevel"/>
	</keypair>
	<keypair>
		<key value="target"/>
		<value value="params" index="0"/>
	</keypair>
	<keypair optional="1">
		<key value="newlevel"></key>
		<value value="params" index="1"></value>
	</keypair>

	<maxParam value="2"></maxParam>
	<minParam value="1"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/JailAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<keypair>
		<key value="type"></key>
		<value value="jail"></value>
	</keypair>
	<keypair>
		<key value="target"/>
		<value value="params" index="0"/>
	</keypair>
	<keypair>
		<key value="minutes"/>
		<value value="params" index="1"/>
	</keypair>
	<keypair>
		<key value="reason"></key>
		<value value="remainder"></value>
	</keypair>
	<maxParam value="2"></maxParam>
	<minParam value="2"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/TeleportAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<keypair>
		<key value = "type"/>
		<value value="teleport"/>
	</keypair>
	<keypair>
		<key value="target"/>
		<value value="params" index="0"/>
	</keypair>
	<keypair>
		<key value="zone"></key>
		<value value="params" index="1"></value>
	</keypair>
	<keypair>
		<key value="x"></key>
		<value value="params" index="2"></value>
	</keypair>
	<keypair>
		<key value="y"></key>
		<value value="params" index="3"></value>
	</keypair>
	<maxParam value="4"></maxParam>
	<minParam value="4"></minParam>
</action>

=== sdacosta13/stendhal_S1Team22/data/conf/actions/AutoWalkStopAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ActionsSchema.xsd">
	<keypair>
		<key value="TYPE"></key>
		<value value="WALK"></value>
	</keypair>
	<keypair>
		<key value="TARGET"></key>
		<value value="remainder"></value>
	</keypair>
	<keypair>
		<key value="MODE"></key>
		<value value="stop"></value>
	</keypair>
	<maxParam value="0"></maxParam>
	<minParam value="0"></minParam>
</action>
